package jb_project1;
// CMSC 330 Advanced Programming Languages
// Project 1 Skeleton
// UMGC CITE
// August 2021

/* 
 * Jordan Burns
 * Jan 26 2024
 * ADDED TOKENS FOR ISOCELESTRIANGLE, TEXT, PARALELLOGRAM, AND REGULAR POLYGON
 * ADDED TOKENS FOR RADIUS, SIDES, AND OFFSET
 */

//Enumerated type that defines the list of tokens
enum Token {AT, COLOR, END,	HEIGHT, RECTANGLE, RIGHT_TRIANGLE, ISOSCELES, TEXT, PARALLELOGRAM, REGULARPOLYGON, SCENE, WIDTH, COMMA, SEMICOLON, PERIOD, LEFT_PAREN,
    RIGHT_PAREN, IDENTIFIER, NUMBER, EOF, OFFSET, SIDES, RADIUS}